table JobSkills
	lineageTag: ad865327-9357-43f0-82fb-eebb7fbb6132

	column 'Job ID'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 4ddd7f4d-e3b6-4e21-b41f-e5d3382e18f1
		summarizeBy: none
		sourceColumn: Job ID

		annotation SummarizationSetBy = User

	column Skill
		dataType: string
		isHidden
		lineageTag: e2dcc788-2399-4422-9e08-002bda0621e7
		summarizeBy: none
		sourceColumn: Skill

		annotation SummarizationSetBy = User

	partition JobSkills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "JobSkills.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers,{{"Job ID", Int64.Type}, {"Skill", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

